groups:
- name: cf-app-sd
  jobs:
  - unit-tests
  - salakot-cats
  - salakot-acceptance-tests
  - salakot-smoke-tests
  - salakot-perf-tests
  - salakot-update-capi
  - salakot-deploy
  - ship-what
  - ship-it
  - bump-patch-version
- name: salakot
  jobs:
  - salakot-bbl-up
  - salakot-bbl-destroy
  - salakot-update-capi
  - salakot-deploy
  - salakot-acceptance-tests
  - salakot-smoke-tests
  - salakot-perf-tests
  - salakot-cats
  - delete-salakot-deployment

resource_types:
- name: staticfile
  type: docker-image
  source:
    repository: czero/staticfile-resource

resources:
  - name: cats-concourse-task
    type: git
    source:
      uri: https://github.com/cloudfoundry/cats-concourse-task
      branch: master
  - name: cf-acceptance-tests
    type: git
    source:
      branch: proxy-app-service-discovery
      uri: git://github.com/cf-container-networking/cf-acceptance-tests.git
  - name: cf-app-sd-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-app-sd-release
      branch: master
  - name: cf-app-sd-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-app-sd-release
      branch: master
      paths:
      - ci
  - name: cf-app-sd-shipped-master
    type: git
    source:
      uri: "git@github.com:cloudfoundry/cf-app-sd-release.git"
      private_key: {{cf-app-sd-deployments-push-key}}
      branch: master
  - name: cf-deployment-concourse-tasks
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
      branch: master
      tag_filter: "v*"
  - name: cf-networking-deployments
    type: git
    source:
      uri: "git@github.com:cloudfoundry/cf-networking-deployments.git"
      branch: master
      private_key: {{cf-networking-deployments-push-key}}
  - name: cf-deployment
    type: git
    source:
      branch: release-candidate
      uri: https://github.com/cloudfoundry/cf-deployment.git
  - name: cf-networking-master
    type: git
    source:
      uri: git@github.com:cloudfoundry/cf-networking-release.git
      branch: master
      ignore_paths:
        - docs
      private_key: {{cf-networking-deploy-key}}
  - name: capi-ci-passed
    type: git
    source:
      uri: https://github.com/cloudfoundry/capi-release
      branch: ci-passed
  - name: capi-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/capi-ci
      branch: master
  - name: capi-version
    type: semver
    source:
      driver: s3
      region_name: us-west-2
      bucket: capi-ci-passed-fake-versions
      key: version
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

  ####### Timers
  - name: every-fifteen-minutes
    type: time
    source:
      interval: 15m
  ####### Release management
  - name: version
    type: semver
    source:
      bucket: {{cf-app-sd-v0.5.x-s3-bucket}}
      region_name: us-west-2
      initial_version: 0.1.0-rc.1
      key: releases/current-version
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: cf-app-sd-tarball
    type: s3
    source:
      bucket: {{cf-app-sd-candidate-s3-bucket}}
      region_name: us-west-2
      regexp: releases/cf-app-sd-(.*).tgz
      key: releases/current-version
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

  - name: cf-app-sd-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: cf-app-sd-release
      access_token: {{github-access-token}}


jobs:
  - name: unit-tests
    plan:
      - aggregate:
          - get: cf-app-sd-release
            trigger: true
          - get: cf-app-sd-ci
      - task: unit-tests
        file: cf-app-sd-ci/ci/tasks/test-unit.yml

  - name: salakot-acceptance-tests
    serial_groups: [salakot-deploy-group, salakot-test-group]
    plan:
      - aggregate:
          - get: cf-networking-deployments
          - get: cf-networking-master
            passed: [salakot-deploy]
          - get: cf-app-sd-release
            passed: [salakot-deploy]
            trigger: true
          - get: cf-app-sd-ci
          - get: cf-deployment
            passed: [salakot-deploy]
            trigger: true
          - get: capi-ci-passed
            passed: [salakot-deploy]
            trigger: true
      - task: salakot-acceptance-tests
        privileged: true
        file: cf-app-sd-ci/ci/tasks/test-acceptance.yml
        input_mapping:
          test-config: cf-networking-deployments
          vars-store: cf-networking-deployments
        params:
          ENVIRONMENT_NAME: salakot

  - name: salakot-smoke-tests
    serial_groups: [salakot-deploy-group, salakot-test-group]
    plan:
      - aggregate:
          - get: every-fifteen-minutes
            trigger: true
          - get: cf-networking-master
            passed: [salakot-deploy]
          - get: cf-networking-deployments
          - get: cf-app-sd-release
            passed: [salakot-deploy]
            trigger: true
          - get: cf-app-sd-ci
          - get: cf-deployment
            passed: [salakot-deploy]
            trigger: true
          - get: capi-ci-passed
            passed: [salakot-deploy]
            trigger: true
      - task: salakot-smoke-tests
        privileged: true
        file: cf-app-sd-ci/ci/tasks/smoke-tests.yml
        input_mapping:
          test-config: cf-networking-deployments
        params:
          ENVIRONMENT_NAME: salakot
          ENVIRONMENT_TAG: salakot.c2c.cf-app.com
          DATADOG_API_KEY: {{datadog_api_key}}

  - name: salakot-cats
    serial_groups: [salakot-deploy-group, salakot-test-group]
    plan:
      - aggregate:
          - get: cf-networking-deployments
          - get: cf-acceptance-tests
          - get: cf-app-sd-ci
          - get: cats-concourse-task
          - get: cf-networking-master
            passed:
            - salakot-smoke-tests
            - salakot-acceptance-tests
            trigger: true
          - get: cf-app-sd-release
            passed:
            - salakot-smoke-tests
            - salakot-acceptance-tests
            trigger: true
          - get: cf-deployment
            passed:
            - salakot-smoke-tests
            - salakot-acceptance-tests
            trigger: true
          - get: capi-ci-passed
            passed:
            - salakot-smoke-tests
            - salakot-acceptance-tests
            trigger: true
      - task: copy-config
        file: cf-app-sd-ci/ci/tasks/copy-config.yml
        params:
          ENVIRONMENT: salakot
      - task: cats
        file: cats-concourse-task/task.yml
        params:
          NODES: 8

  - name: salakot-perf-tests
    serial_groups: [salakot-deploy-group, salakot-test-group]
    plan:
      - aggregate:
          - get: cf-networking-master
            passed:
            - salakot-smoke-tests
            - salakot-acceptance-tests
          - get: cf-networking-deployments
          - get: cf-app-sd-release
            passed:
            - salakot-smoke-tests
            - salakot-acceptance-tests
            trigger: true
          - get: cf-app-sd-ci
          - get: cf-deployment
            passed:
            - salakot-smoke-tests
            - salakot-acceptance-tests
            trigger: true
      - task: salakot-perf-tests
        privileged: true
        file: cf-app-sd-ci/ci/tasks/test-nats-performance.yml
        input_mapping:
          test-config: cf-networking-deployments
          deployments-repo: cf-networking-deployments
        params:
          ENVIRONMENT_NAME: salakot

  - name: salakot-bbl-up
    serial_groups: [salakot-deploy-group, salakot-test-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
            trigger: true
          - get: cf-networking-deployments
      - task: bbl-up
        file: cf-deployment-concourse-tasks/bbl-up/task.yml
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: environments/gcp/service-account.key.json
          BBL_GCP_REGION: us-east1
          BBL_STATE_DIR: environments/salakot/
          BBL_IAAS: gcp
          BBL_LB_CERT: {{salakot-lb-cert}}
          BBL_LB_KEY: {{salakot-lb-key}}
          LB_DOMAIN: salakot.c2c.cf-app.com
          BBL_ENV_NAME: salakot
          OPS_FILES: local-dns.yml
        input_mapping:
          env-repo: cf-networking-deployments
          ops-files: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-env-repo
            rebase: true

  - name: salakot-bbl-destroy
    serial_groups: [salakot-deploy-group, salakot-test-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
      - task: bosh-cleanup
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        params:
          BBL_STATE_DIR: environments/salakot/
        input_mapping:
          env-repo: cf-networking-deployments
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: environments/salakot/
          BBL_GCP_SERVICE_ACCOUNT_KEY: environments/gcp/service-account.key.json
        input_mapping:
          env-repo: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-env-repo
            rebase: true

  - name: salakot-update-capi
    serial_groups: [salakot-deploy-group]
    plan:
      - aggregate:
          - get: cf-networking-deployments
          - get: capi-ci-passed
            trigger: true
          - get: capi-ci
          - get: capi-version
            params: {bump: patch}
          - get: cf-app-sd-ci
      - task: create-capi-release
        file: capi-ci/ci/bosh/create_capi_release.yml
        input_mapping:
          capi-release: capi-ci-passed
          version: capi-version
          cloud_controller_ng: capi-version # does not matter, we won't use this
      - task: upload-capi-release
        file: cf-app-sd-ci/ci/tasks/upload-release-tarball.yml
        input_mapping:
          tarballs: created-capi-release
          deployments-repo: cf-networking-deployments
        params:
          ENVIRONMENT_NAME: salakot
      - put: capi-version
        params: {file: capi-version/version}

  - name: salakot-deploy
    serial_groups: [salakot-deploy-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
          - get: cf-deployment
            trigger: true
          - get: cf-networking-master
          - get: cf-app-sd-release
            trigger: true
            passed: [unit-tests]
          - get: cf-app-sd-ci
          - get: capi-ci-passed
            passed: [salakot-update-capi]
            trigger: true
      - task: upload-stemcell
        file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
        params:
          BBL_STATE_DIR: environments/salakot/
        input_mapping:
          env-repo: cf-networking-deployments
      - task: collect-ops-files
        file: cf-app-sd-ci/ci/tasks/collect-ops-files.yml
        params:
          ENVIRONMENT_NAME: salakot
        input_mapping:
          cf-networking-release: cf-networking-master
          deployments-repo: cf-networking-deployments
      - task: upload-local-cf-app-sd-releases
        file: cf-app-sd-ci/ci/tasks/upload-local-release.yml
        input_mapping:
          env-repo: cf-networking-deployments
          local-release: cf-app-sd-release
        params:
          BBL_STATE_DIR: environments/salakot/
      - task: deploy-cf
        file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
        params:
          BBL_STATE_DIR: environments/salakot/
          SYSTEM_DOMAIN: salakot.c2c.cf-app.com
          OPS_FILES: use-compiled-releases.yml scale-to-one-az.yml smaller-footprint.yml datadog.yml use-bosh-dns-for-containers.yml use-bosh-dns.yml use-latest-capi.yml use-system-domain-as-metron-deployment-name.yml enable-service-discovery.yml use-latest.yml opsfile.yml
          VARS_STORE_FILE: environments/salakot/vars-store.yml
        input_mapping:
          env-repo: cf-networking-deployments
          release: cf-app-sd-release
          vars-files: cf-networking-deployments
          vars-store: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-vars-store
            rebase: true
      - task: bosh-cleanup
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        params:
          BBL_STATE_DIR: environments/salakot/
        input_mapping:
          env-repo: cf-networking-deployments

  - name: delete-salakot-deployment
    serial_groups: [salakot-deploy-group, salakot-test-group]
    plan:
    - aggregate:
      - get: cf-networking-deployments
      - get: cf-deployment-concourse-tasks
    - task: delete-deployment
      file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
      params:
        BBL_STATE_DIR: environments/salakot/
      input_mapping:
        env-repo: cf-networking-deployments

  - name: ship-what
    serial_groups: [version]
    plan:
    - do:
      - aggregate:
        - get: version
          passed: [salakot-deploy]
        - get: cf-networking-master
          params:
            submodules: none
          passed: [salakot-deploy]
        - get: cf-app-sd-release
          passed: [salakot-deploy]
          trigger: true
        - get: cf-deployment
          passed: [salakot-deploy]
        - get: cf-app-sd-tarball
          passed: [salakot-deploy]

  - name: ship-it
    serial_groups: [version]
    plan:
    - do:
      - aggregate:
        - get: version
          params:
            bump: final
          passed: [ship-what]
        - get: cf-app-sd-tarball
          passed: [ship-what]
        - get: cf-app-sd-ci
        - get: cf-app-sd-release
          passed: [ship-what]
        - get: cf-app-sd-shipped-master
        - get: cf-networking-deployments
      - task: ship-it
        file: cf-app-sd-ci/ci/tasks/ship-it.yml
      - put: version
        params: {file: version/number}
      - put: cf-app-sd-shipped-master
        params:
          repository: release/master
      - put: cf-app-sd-shipped-master
        params:
          repository: cf-app-sd-release
          tag: version/number
          tag_prefix: v
          only_tag: true

  # bump patch version (i.e. 0.0.1 -> 0.0.2)
  - name: bump-patch-version
    serial_groups: [version]
    plan:
    - get: version
      trigger: true
      passed: [ship-it]
      params: {bump: patch, pre: rc}
    - put: version
      params: {file: version/number}
