---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

inputs:
  - name: cf-deployment
  - name: cf-app-sd-ci
  - name: cf-app-sd-shipped-master

outputs:
  - name: release-notes

run:
  path: cf-app-sd-ci/ci/tasks/build-release-notes

params:
  SOURCE_DIR: cf-app-sd-shipped-master
  OUTPUT_DIR: release-notes
