#!/bin/bash

set -e -u

cp cf-deployment/operations/**/*.yml ops-files/
cp cf-deployment/operations/*.yml ops-files/

cp cf-app-sd-release/opsfiles/enable-service-discovery.yml ops-files/

cp deployments-repo/environments/${ENVIRONMENT_NAME}/opsfile*.yml ops-files/ || true # if we don't have an env specific opsfile

cp cf-app-sd-release/ci/opsfiles/*.yml ops-files/
