#!/bin/bash

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp cf-networking-deployments/cf-app-sd/config/private.yml cf-app-sd-shipped-master/config/private.yml

CANDIDATE_DIR=$PWD/cf-app-sd-tarball
cd cf-app-sd-shipped-master

git fetch --tags
if [[ -n "$(git tag | grep -E "^${VERSION}$")" ]]; then
  echo "git tag ${VERSION} already exists. Nothing has been tagged or commited. Fast failing..."
  exit 1
fi

git config --global user.email "container-networking+ci@pivotal.io"
git config --global user.name "Container Networking Bot"

RELEASE_YML=$PWD/releases/cf-app-sd/cf-app-sd-${VERSION}.yml

if [ -e ${RELEASE_YML} ]; then
  echo "release already created; making tarball..."
  bosh -n create-release --tarball=../final-release/cf-app-sd-${VERSION}.tgz ${RELEASE_YML}
else
  echo "finalizing release"
  bosh -n finalize-release --version="$VERSION" ${CANDIDATE_DIR}/cf-app-sd-*.tgz
  git add -A
  git commit -m "Release v${VERSION}"
  bosh create-release --tarball ../final-release/cf-app-sd-${VERSION}.tgz releases/cf-app-sd/cf-app-sd-${VERSION}.yml
fi

cp -r . ../release/master
