#!/bin/bash

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp cf-networking-deployments/cf-app-sd/config/private.yml cf-app-sd-shipped-master/config/private.yml

CANDIDATE_DIR=$PWD/cf-app-sd-tarball
cd cf-app-sd-shipped-master

git config --global user.email "container-networking+ci@pivotal.io"
git config --global user.name "Container Networking Bot"

git tag -a "v${VERSION}" -m "tagging branch version"
