---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: version
  - name: cf-app-sd-ci
  - name: cf-networking-deployments

run:
  path: cf-app-sd-ci/ci/tasks/ship-it
