#!/bin/bash

set -euo pipefail

# Targetting director
pushd "deployments-repo/environments/$ENVIRONMENT_NAME"
  BOSH_ENVIRONMENT="$(bbl director-address)"
  export BOSH_ENVIRONMENT
  BOSH_CLIENT_SECRET="$(bbl director-password)"
  export BOSH_CLIENT_SECRET
  BOSH_CLIENT="$(bbl director-username)"
  export BOSH_CLIENT
  bbl director-ca-cert > /tmp/ca.crt
  export BOSH_CA_CERT=/tmp/ca.crt
  export BOSH_DEPLOYMENT=concourse
popd


export GOPATH=$PWD/service-discovery-release
export PATH="${GOPATH}/bin":$PATH

go install github.com/onsi/ginkgo/ginkgo

export CONFIG="$PWD/deployments-repo/environments/$ENVIRONMENT_NAME/perf-config.json"

pushd service-discovery-release/src/performance
   ginkgo -race deploy/
   bosh -d performance run-errand performance-tests
   bosh -n -d performance delete-deployment
popd
