---
# cf-deployment uses system_domain as metron agent deployment.
# Use this to override metron agent deployment name in the metron_agent addon
- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/tags?
  value: {"deployment": "((system_domain))"}

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/deployment?
  value: ((system_domain))
