#!/bin/bash
set -e -u

ROOT_DIR_PATH="$(cd $(dirname $0)/.. && pwd)"
cd ${ROOT_DIR_PATH}

docker run \
   -it \
   -v ${PWD}:/service-discovery-release \
   -e GOPATH=/service-discovery-release \
   -w / \
   golang:1.8 \
   /bin/bash "$@"

