#!/bin/bash
set -e -u

ROOT_DIR_PATH="$(cd $(dirname $0)/.. && pwd)"
cd ${ROOT_DIR_PATH}

docker run \
   -it \
   -v ${PWD}:/cf-app-sd-release \
   -e GOPATH=/cf-app-sd-release \
   -w / \
   golang:1.10 \
   /bin/bash "$@"

