#!/bin/bash

set -e -u
export PIPELINE="cf-app-sd-v0.5.x"
export TARGET=c2c

fly -t $TARGET \
  set-pipeline -p $PIPELINE \
  -c $HOME/workspace/cf-app-sd-release/ci/pipelines/$PIPELINE.yml \
  -l $HOME/workspace/cf-networking-deployments/pipeline-credentials.yml
